// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNjyPuyhv4E0p_4aIK-86J6Jum3M76T74',
    appId: '1:294432244859:web:e2c9d42c022159bd0e8ede',
    messagingSenderId: '294432244859',
    projectId: 'flutter-test-ed42c',
    authDomain: 'flutter-test-ed42c.firebaseapp.com',
    storageBucket: 'flutter-test-ed42c.appspot.com',
    measurementId: 'G-YXTJ48W09B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFByUCxX3SkAKrXW2IoJmsMrAfFsSSJoY',
    appId: '1:294432244859:android:8211210f39851b1b0e8ede',
    messagingSenderId: '294432244859',
    projectId: 'flutter-test-ed42c',
    storageBucket: 'flutter-test-ed42c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANrFoJSRIA0EAG_kab7AVFxGfnSEkT4hc',
    appId: '1:294432244859:ios:f87281f7434b9a290e8ede',
    messagingSenderId: '294432244859',
    projectId: 'flutter-test-ed42c',
    storageBucket: 'flutter-test-ed42c.appspot.com',
    iosClientId:
        '294432244859-e4bqf2tucne3q3rmgodnkamm6ndjfn35.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterVpn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANrFoJSRIA0EAG_kab7AVFxGfnSEkT4hc',
    appId: '1:294432244859:ios:f87281f7434b9a290e8ede',
    messagingSenderId: '294432244859',
    projectId: 'flutter-test-ed42c',
    storageBucket: 'flutter-test-ed42c.appspot.com',
    iosClientId:
        '294432244859-e4bqf2tucne3q3rmgodnkamm6ndjfn35.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterVpn',
  );
}
